#!/usr/bin/env python3
"""
create_vault.py — Generate a small, deterministic Obsidian vault for visual tests.

Usage:
    create_vault.py <vault-dir> [--plugin-dir <built-plugin-dir>] [--enable-plugin]

What it generates:
    <vault-dir>/
        Welcome.md                 — landing note with links + code block
        Daily/2026-04-16.md        — sample daily note
        Notes/Project Plan.md      — note with table + headings
        Notes/Meeting Notes.md     — note with tasks + tags
        Reference/API.md           — note with nested lists
        .obsidian/
            app.json
            appearance.json
            community-plugins.json — enables obsidian-mcp if --enable-plugin
            core-plugins.json
            workspace.json         — opens Welcome.md by default
            plugins/obsidian-mcp/  — copied from --plugin-dir if given

The content is deliberately small but varied so screenshots cover code blocks,
tables, lists, links, and tags — useful surfaces for visual regression checks.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

NOTES: dict[str, str] = {
    "Welcome.md": """# Welcome to the Test Vault

This vault is generated by `create_vault.py` for visual regression testing.

## Quick Links

- [[Notes/Project Plan]]
- [[Notes/Meeting Notes]]
- [[Reference/API]]
- [[Daily/2026-04-16]]

## Sample Code

```typescript
import { Plugin } from 'obsidian';

export default class ExamplePlugin extends Plugin {
    async onload() {
        console.log('loaded');
    }
}
```

> Use this vault for before/after screenshot tests.
""",
    "Daily/2026-04-16.md": """# 2026-04-16

## Today

- [ ] Review PRs
- [x] Ship visual regression setup
- [ ] Update changelog

## Notes

Worked on the docker visual-test pipeline.
""",
    "Notes/Project Plan.md": """# Project Plan

## Phases

| Phase | Status | Owner |
|-------|--------|-------|
| Design | Done | Alice |
| Build | In progress | Bob |
| Test | Blocked | Carol |
| Ship | Pending | — |

## Risks

1. Schedule slippage
2. Dependency on external API
3. Test coverage gaps
""",
    "Notes/Meeting Notes.md": """# Meeting Notes

#meeting #sprint-7

## Attendees

- Alice
- Bob
- Carol

## Action Items

- [ ] Alice: draft RFC
- [ ] Bob: prototype the MCP server
- [ ] Carol: write test plan

## Decisions

- Use Streamable HTTP for transport
- Adopt Conventional Commits
""",
    "Reference/API.md": """# API Reference

## Endpoints

- `GET /mcp/tools` — list tools
  - Response: JSON array of tool descriptors
  - Auth: bearer token required
- `POST /mcp/invoke` — invoke a tool
  - Body: `{ tool: string, args: object }`
  - Response: tool result
- `GET /mcp/health` — health check
  - Response: `{ status: "ok" }`

## Tool Categories

- vault — file operations
- editor — buffer mutations
- search — query the vault
- workspace — leaf/tab control
""",
}


def write_vault(vault_dir: Path, plugin_dir: Path | None, enable_plugin: bool) -> None:
    vault_dir.mkdir(parents=True, exist_ok=True)

    # Notes
    for rel, body in NOTES.items():
        target = vault_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")

    # .obsidian config
    obs = vault_dir / ".obsidian"
    obs.mkdir(exist_ok=True)

    (obs / "app.json").write_text(
        json.dumps(
            {
                "alwaysUpdateLinks": True,
                "newFileLocation": "current",
                "showLineNumber": True,
                "promptDelete": False,
            },
            indent=2,
        )
    )
    (obs / "appearance.json").write_text(
        json.dumps(
            {"baseFontSize": 16, "interfaceFontSize": 14, "theme": "obsidian"},
            indent=2,
        )
    )
    (obs / "core-plugins.json").write_text(
        json.dumps(
            {
                "file-explorer": True,
                "global-search": True,
                "switcher": True,
                "graph": True,
                "backlink": True,
                "outgoing-link": True,
                "tag-pane": True,
                "page-preview": True,
                "daily-notes": True,
                "templates": True,
                "command-palette": True,
                "editor-status": True,
                "outline": True,
                "word-count": True,
            },
            indent=2,
        )
    )
    (obs / "community-plugins.json").write_text(
        json.dumps(["obsidian-mcp"] if enable_plugin else [], indent=2)
    )

    # Workspace: open Welcome.md by default
    (obs / "workspace.json").write_text(
        json.dumps(
            {
                "main": {
                    "id": "main-split",
                    "type": "split",
                    "children": [
                        {
                            "id": "main-tabs",
                            "type": "tabs",
                            "children": [
                                {
                                    "id": "welcome-leaf",
                                    "type": "leaf",
                                    "state": {
                                        "type": "markdown",
                                        "state": {"file": "Welcome.md", "mode": "preview"},
                                    },
                                }
                            ],
                        }
                    ],
                    "direction": "vertical",
                },
                "active": "welcome-leaf",
            },
            indent=2,
        )
    )

    # Install built plugin
    if plugin_dir is not None:
        plugin_target = obs / "plugins" / "obsidian-mcp"
        plugin_target.mkdir(parents=True, exist_ok=True)
        for fname in ("main.js", "manifest.json", "styles.css"):
            src = plugin_dir / fname
            if src.exists():
                shutil.copy2(src, plugin_target / fname)
            elif fname == "styles.css":
                # styles.css is optional but Obsidian expects the file to exist
                (plugin_target / fname).touch()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vault_dir", help="Where to create the vault")
    parser.add_argument(
        "--plugin-dir",
        default=None,
        help="Directory containing built main.js + manifest.json to install",
    )
    parser.add_argument(
        "--enable-plugin",
        action="store_true",
        help="Also list obsidian-mcp in community-plugins.json (still requires "
        "Restricted Mode to be off — bootstrap.py handles that)",
    )
    args = parser.parse_args()

    plugin_dir = Path(args.plugin_dir) if args.plugin_dir else None
    write_vault(Path(args.vault_dir), plugin_dir, args.enable_plugin)
    print(f"Vault created at {args.vault_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
