/**
 * Composes the per-module pages and the index page that together form
 * `docs/tools.generated.md` + `docs/tools/<module>.generated.md`. Pure
 * string functions — file I/O lives in `scripts/list-tools.ts`.
 */

import { z } from 'zod';
import { inputShapeToTable, outputSchemaToTables } from './schema-to-table';

export interface ToolDoc {
  name: string;
  title: string;
  description: string;
  schema: z.ZodRawShape;
  outputSchema: z.ZodRawShape | z.ZodTypeAny | undefined;
}

export interface ModuleDoc {
  moduleId: string;
  moduleName: string;
  tools: ToolDoc[];
}

const BANNER =
  '<!-- AUTO-GENERATED by `npm run docs:tools`. Do not edit manually. -->';

export function renderModulePage(module: ModuleDoc): string {
  const lines: string[] = [];
  lines.push(BANNER);
  lines.push('');
  lines.push(`# ${module.moduleName} (\`${module.moduleId}\`)`);
  lines.push('');
  lines.push(
    `Auto-generated schema reference for the \`${module.moduleId}\` module. See [../tools.generated.md](../tools.generated.md) for the full registry index.`,
  );
  lines.push('');

  for (const tool of module.tools) {
    lines.push(`### ${tool.name}`);
    lines.push('');
    lines.push(`**${tool.title}**`);
    lines.push('');
    lines.push(tool.description.trim());
    lines.push('');
    lines.push('#### Input');
    lines.push('');
    lines.push(inputShapeToTable(tool.schema));
    lines.push('');
    lines.push('#### Output');
    lines.push('');
    lines.push(outputSchemaToTables(tool.outputSchema));
    lines.push('');
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}
