/**
 * Composes the per-module pages and the index page that together form
 * `docs/tools.generated.md` + `docs/tools/<module>.generated.md`. Pure
 * string functions — file I/O lives in `scripts/list-tools.ts`.
 */

import { z } from 'zod';
import { inputShapeToTable, outputSchemaToTables } from './schema-to-table';

export interface ToolDoc {
  name: string;
  title: string;
  description: string;
  schema: z.ZodRawShape;
  outputSchema: z.ZodRawShape | z.ZodTypeAny | undefined;
  readOnly: boolean;
  destructive: boolean;
}

export interface ModuleDoc {
  moduleId: string;
  moduleName: string;
  tools: ToolDoc[];
}

const BANNER =
  '<!-- AUTO-GENERATED by `npm run docs:tools`. Do not edit manually. -->';

function check(value: boolean): string {
  return value ? '✓' : '';
}

export function renderIndexPage(modules: ModuleDoc[]): string {
  const lines: string[] = [];
  lines.push(BANNER);
  lines.push('');
  lines.push('# Tool Registry Snapshot');
  lines.push('');
  lines.push(
    'This file is regenerated from the tool registry and committed so CI can detect doc drift.',
  );
  lines.push('');

  // Summary table — preserved verbatim from the previous renderer.
  lines.push('| Module ID | Module Name | Count | Tools |');
  lines.push('|---|---|---|---|');
  let total = 0;
  for (const m of modules) {
    total += m.tools.length;
    const names = m.tools.map((t) => t.name).join(', ');
    lines.push(
      `| \`${m.moduleId}\` | ${m.moduleName} | ${String(m.tools.length)} | ${names} |`,
    );
  }
  lines.push('');
  lines.push(`**Total tools:** ${String(total)} across ${String(modules.length)} modules.`);
  lines.push('');

  // Per-module annotation tables, each prefixed by the schema link.
  lines.push('## Tools by module');
  lines.push('');
  for (const m of modules) {
    lines.push(`### ${m.moduleName} (\`${m.moduleId}\`)`);
    lines.push('');
    lines.push(
      `Schemas → [docs/tools/${m.moduleId}.generated.md](tools/${m.moduleId}.generated.md)`,
    );
    lines.push('');
    lines.push('| Name | Title | readOnly | destructive |');
    lines.push('|---|---|---|---|');
    for (const t of m.tools) {
      lines.push(
        `| \`${t.name}\` | ${t.title} | ${check(t.readOnly)} | ${check(t.destructive)} |`,
      );
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

export function renderModulePage(module: ModuleDoc): string {
  const lines: string[] = [];
  lines.push(BANNER);
  lines.push('');
  lines.push(`# ${module.moduleName} (\`${module.moduleId}\`)`);
  lines.push('');
  lines.push(
    `Auto-generated schema reference for the \`${module.moduleId}\` module. See [../tools.generated.md](../tools.generated.md) for the full registry index.`,
  );
  lines.push('');

  for (const tool of module.tools) {
    lines.push(`### ${tool.name}`);
    lines.push('');
    lines.push(`**${tool.title}**`);
    lines.push('');
    lines.push(tool.description.trim());
    lines.push('');
    lines.push('#### Input');
    lines.push('');
    lines.push(inputShapeToTable(tool.schema));
    lines.push('');
    lines.push('#### Output');
    lines.push('');
    lines.push(outputSchemaToTables(tool.outputSchema));
    lines.push('');
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}
