/**
 * Walk the tool registry and emit a markdown snapshot of every module and
 * its tools. Used as the source of truth for `docs/tools.generated.md` so
 * CI can detect drift between the code and the documentation.
 *
 * Run via `npm run docs:tools`.
 */

import { writeFileSync } from 'node:fs';
import { argv } from 'node:process';
import { MockObsidianAdapter } from '../src/obsidian/mock-adapter';
import { discoverModules } from '../src/tools';

interface ToolEntry {
  name: string;
  title: string;
  readOnly: boolean;
  destructive: boolean;
}

interface ToolRow {
  moduleId: string;
  moduleName: string;
  tools: ToolEntry[];
}

export function collectToolRows(): ToolRow[] {
  const adapter = new MockObsidianAdapter();
  const modules = discoverModules(adapter);
  return modules.map((module) => ({
    moduleId: module.metadata.id,
    moduleName: module.metadata.name,
    tools: module.tools().map((t) => ({
      name: t.name,
      title: t.title,
      readOnly: t.annotations.readOnlyHint === true,
      destructive: t.annotations.destructiveHint === true,
    })),
  }));
}

function check(value: boolean): string {
  return value ? '✓' : '';
}

export function renderMarkdown(rows: ToolRow[]): string {
  const lines: string[] = [];
  lines.push('<!-- AUTO-GENERATED by `npm run docs:tools`. Do not edit manually. -->');
  lines.push('');
  lines.push('# Tool Registry Snapshot');
  lines.push('');
  lines.push(
    'This file is regenerated from the tool registry and committed so CI can detect doc drift.',
  );
  lines.push('');

  // Summary table — preserved for backward compatibility with existing tests.
  lines.push('| Module ID | Module Name | Count | Tools |');
  lines.push('|---|---|---|---|');

  let total = 0;
  for (const row of rows) {
    total += row.tools.length;
    const tools = row.tools.map((t) => t.name).join(', ');
    lines.push(
      `| \`${row.moduleId}\` | ${row.moduleName} | ${String(row.tools.length)} | ${tools} |`,
    );
  }

  lines.push('');
  lines.push(`**Total tools:** ${String(total)} across ${String(rows.length)} modules.`);
  lines.push('');

  // Per-module detail tables — new in #289. Surfaces the three Directory
  // hard-pass criteria (title + readOnlyHint + destructiveHint) per tool.
  lines.push('## Tools by module');
  lines.push('');
  for (const row of rows) {
    lines.push(`### ${row.moduleName} (\`${row.moduleId}\`)`);
    lines.push('');
    lines.push('| Name | Title | readOnly | destructive |');
    lines.push('|---|---|---|---|');
    for (const t of row.tools) {
      lines.push(
        `| \`${t.name}\` | ${t.title} | ${check(t.readOnly)} | ${check(t.destructive)} |`,
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

function main(): void {
  const outPath = argv[2] ?? 'docs/tools.generated.md';
  const rows = collectToolRows();
  const markdown = renderMarkdown(rows);
  writeFileSync(outPath, markdown);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath} (${String(rows.length)} modules, ${String(rows.reduce((n, r) => n + r.tools.length, 0))} tools)`);
}

if (import.meta.url === `file://${argv[1]}`) {
  main();
}
