/**
 * Walk the tool registry and emit a markdown snapshot of every module and
 * its tools. Used as the source of truth for `docs/tools.generated.md` so
 * CI can detect drift between the code and the documentation.
 *
 * Run via `npm run docs:tools`.
 */

import { writeFileSync } from 'node:fs';
import { argv } from 'node:process';
import { MockObsidianAdapter } from '../src/obsidian/mock-adapter';
import { discoverModules } from '../src/tools';

interface ToolRow {
  moduleId: string;
  moduleName: string;
  tools: string[];
}

export function collectToolRows(): ToolRow[] {
  const adapter = new MockObsidianAdapter();
  const modules = discoverModules(adapter);
  return modules.map((module) => ({
    moduleId: module.metadata.id,
    moduleName: module.metadata.name,
    tools: module.tools().map((t) => t.name),
  }));
}

export function renderMarkdown(rows: ToolRow[]): string {
  const lines: string[] = [];
  lines.push('<!-- AUTO-GENERATED by `npm run docs:tools`. Do not edit manually. -->');
  lines.push('');
  lines.push('# Tool Registry Snapshot');
  lines.push('');
  lines.push(
    'This file is regenerated from the tool registry and committed so CI can detect doc drift.',
  );
  lines.push('');
  lines.push('| Module ID | Module Name | Count | Tools |');
  lines.push('|---|---|---|---|');

  let total = 0;
  for (const row of rows) {
    total += row.tools.length;
    const tools = row.tools.join(', ');
    lines.push(
      `| \`${row.moduleId}\` | ${row.moduleName} | ${String(row.tools.length)} | ${tools} |`,
    );
  }

  lines.push('');
  lines.push(`**Total tools:** ${String(total)} across ${String(rows.length)} modules.`);
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const outPath = argv[2] ?? 'docs/tools.generated.md';
  const rows = collectToolRows();
  const markdown = renderMarkdown(rows);
  writeFileSync(outPath, markdown);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath} (${String(rows.length)} modules, ${String(rows.reduce((n, r) => n + r.tools.length, 0))} tools)`);
}

// Execute when run directly (not when imported for testing).
if (import.meta.url === `file://${argv[1]}`) {
  main();
}
